# Generated by Django 5.2.17 on 2026-08-04 17:03

import apps.sala.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_key', models.SlugField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('destino_tipo', models.CharField(choices=[('nativo', 'Nativo'), ('externo_servidor', 'Externo (servidor)'), ('externo_pc_local', 'Externo (PC local)')], max_length=20)),
                ('dominio', models.CharField(blank=True, max_length=255)),
                ('workspace_api_key', apps.sala.fields.EncryptedTextField(blank=True, null=True)),
                ('connection_token_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token_generado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntradaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_key', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('subpath', models.CharField(blank=True, max_length=255)),
                ('uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('entry', models.JSONField()),
                ('mtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['mtime'],
                'indexes': [models.Index(fields=['project_key', 'session_id', 'subpath'], name='sala_entrad_project_bd7d47_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='sala.proyecto')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_input', models.JSONField()),
                ('title', models.TextField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('denegado', 'Denegado'), ('caducado', 'Caducado')], default='pendiente', max_length=20)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_permiso', to='sala.chat')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
