# Generated by Django 5.2.17 on 2026-08-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_seed_ia_central_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='session_id',
            new_name='consultor_session_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='agente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='rama',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SesionEjecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acp_session_id', models.CharField(blank=True, max_length=255)),
                ('slot', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_cola', 'En cola'), ('activa', 'Activa'), ('terminada', 'Terminada'), ('caducada', 'Caducada')], default='en_cola', max_length=20)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('terminada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_ejecutor', to='sala.chat')),
            ],
            options={
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('slot',), name='un_solo_ejecutor_activo_por_slot'), models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('chat',), name='un_solo_ejecutor_activo_por_chat')],
            },
        ),
    ]
