# Generated by Django 5.2.17 on 2026-08-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_rename_session_id_chat_consultor_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='description',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='title',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='tool_input',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='tool_name',
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='motivo_cierre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='opcion_elegida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='opciones',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('caducada', 'Caducada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='LlamadaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_call_id', models.CharField(max_length=255)),
                ('title', models.TextField(blank=True)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_input', models.JSONField(blank=True, null=True)),
                ('raw_output', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas', to='sala.sesionejecutor')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='llamada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='sala.llamadaherramienta'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActualizacionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='sala.sesionejecutor')),
            ],
            options={
                'ordering': ['recibido_en'],
                'indexes': [models.Index(fields=['sesion', 'recibido_en'], name='sala_actual_sesion__637a55_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='llamadaherramienta',
            constraint=models.UniqueConstraint(fields=('sesion', 'tool_call_id'), name='tool_call_unico_por_sesion'),
        ),
    ]
