# Generated by Django 5.2.17 on 2026-08-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0004_remove_solicitudpermiso_agent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='consultor_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
